CREATE TABLE topics (
  id SERIAL PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  description TEXT
);
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(16) NOT NULL UNIQUE,
  password VARCHAR,
  github_id BIGINT UNIQUE,
  github_url VARCHAR,
  avatar_url VARCHAR
);
CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 'f',
  author INT NOT NULL REFERENCES users(id),
  topics INT [] NOT NULL,
  create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ups INT NOT NULL DEFAULT 0,
  downs INT NOT NULL DEFAULT 0
);
CREATE TABLE posts_thumbs (
  id SERIAL PRIMARY KEY,
  post INT NOT NULL REFERENCES posts(id),
  author INT NOT NULL REFERENCES users(id),
  voting BOOLEAN,
  create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post INT REFERENCES posts(id),
  author INT NOT NULL REFERENCES users(id)
);