CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(16) NOT NULL,
  password VARCHAR NOT NULL
);
CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 'f',
  author INT NOT NULL REFERENCES users(id),
  create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post INT REFERENCES posts(id),
  author INT NOT NULL REFERENCES users(id)
);